name: Scheduled Stable Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_stable_releases:
    name: Check for new stable release
    runs-on: ubuntu-latest
    outputs:
      build_ref: ${{ steps.check.outputs.build_ref }}
      release_tag: ${{ steps.check.outputs.release_tag }}
      release_body: ${{ steps.check.outputs.release_body }}
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check releases
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/check-releases.sh ${{ github.repository }}

  trigger_build:
    name: Build
    needs: check_stable_releases
    if: ${{ needs.check_stable_releases.outputs.should_build == 'true' }}
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.check_stable_releases.outputs.build_ref }}

  trigger_release:
    name: Release
    needs: [check_stable_releases, trigger_build]
    if: always() && needs.check_stable_releases.result == 'success'
    uses: ./.github/workflows/release.yml
    with:
      is_prerelease: false
      release_tag: ${{ needs.check_stable_releases.outputs.release_tag }}
      release_body: ${{ needs.check_stable_releases.outputs.release_body }}
    permissions:
      contents: write
